### ISSUE TITLE
Exercise about shapeless Record was disabled

### ISSUE THREAD

**Issue by franciscodr** [scala-exercises/exercises-doobie#9]
A exercise about shapeless Record was disabled because of the following compilation error:

```
Exception in thread "evaluation-scheduler-0" java.lang.NoClassDefFoundError: shapeless/syntax/RecordOps$
```

The exercise should be enabled once the evaluator error is fixed.

**Comment by raulraja** [comment]
@franciscodr This should no longer be an issue since we are using the remote evaluator that loads everything on its own classloader. Can you verify and close accordingly?

**Comment by franciscodr** [comment]
@raulraja Yes, there is an open pull request that fixes this issue: https://github.com/scala-exercises/exercises-doobie/pull/14.

I'll merge it once it is reviewed
